# https://cloudhack.jp/posts/github-actions/curriculum-vitae/
name: マークダウンからPDFを生成する

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: チェックアウトする
        uses: actions/checkout@v2

      - name: 日本語フォントの導入
        run: sudo apt install fonts-ipafont fonts-ipaexfont

      - name: Node.js ${{ matrix.node-version }} を利用する
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPMモジュールを準備する
        run: npm ci

      - name: マークダウンをPDFに変換する
        run: npm start

      - name: 生成したファイルをGitにコミットする
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-A'
          commit_message: PDFファイルの自動生成