# https://cloudhack.jp/posts/github-actions/curriculum-vitae/
name: Generate CV PDF

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Japanese font
        run: sudo apt install fonts-ipafont fonts-ipaexfont

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm setup
        run: npm ci

      - name: Convert markdowns in 'src' to pdf in 'dist'
        run: npm start

      - name: Commit output pdf files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-A'
          commit_message: PDFファイルの自動生成